"""
Homomorphic Decryption transformer — decryption as a policy action.

Only components whose Permit.io role grants them a pipeline containing this
transformer will receive plaintext values. All others pass through the
encrypted blob unchanged.
"""
import base64
import logging
import os
import socket
import struct
from typing import Any

import tenseal as ts

from src.transformers.base import BaseTransformer

logger = logging.getLogger(__name__)


class HomomorphicDecryptionTransformer(BaseTransformer):
    """
    Decrypt CKKS-encrypted fields back to plaintext scalars.

    Requires the secret key generated by HomomorphicEncryptionTransformer.
    Fields that are not FHE blobs are passed through unchanged.
    """

    def __init__(self, fields: list[str], key_dir: str = "./fhe_keys"):
        self.fields = set(fields)
        self.key_dir = key_dir
        self._secret_context = self._load_secret_context(key_dir)

    def _load_secret_context(self, key_dir: str) -> ts.Context:
        secret_path = os.path.join(key_dir, "ckks_secret.bin")
        if not os.path.exists(secret_path):
            raise FileNotFoundError(
                f"CKKS secret key not found at {secret_path}. "
                "Generate keys first by instantiating HomomorphicEncryptionTransformer."
            )
        with open(secret_path, "rb") as f:
            return ts.context_from(f.read())

    @staticmethod
    def _restore_type(val: float, original_type: str | None) -> Any:
        """Convert a decrypted CKKS float back to the original Python type/format."""
        if original_type == "ipv4":
            try:
                packed = struct.pack("!I", int(round(val * 4294967295.0)))
                return socket.inet_ntoa(packed)
            except (struct.error, socket.error, OSError):
                return val
        if original_type == "int":
            return int(round(val))
        if original_type == "bool":
            return bool(round(val))
        return val  # "float", "str_float", None → return as-is

    async def transform(self, data: dict[str, Any]) -> dict[str, Any]:
        result = data.copy()
        encrypted_fields: list[str] = list(result.get("__fhe_encrypted_fields__") or [])
        still_encrypted: list[str] = []

        for field in self.fields:
            blob = result.get(field)
            if not isinstance(blob, dict) or not blob.get("__fhe__"):
                still_encrypted.append(field) if field in encrypted_fields else None
                continue

            try:
                # Support both direct wire format ("ciphertext") and
                # aggregated format from MetricProfile ("mean" holds the encrypted mean)
                ct_key = "ciphertext" if "ciphertext" in blob else "mean"
                raw = base64.b64decode(blob[ct_key])
                enc = ts.ckks_vector_from(self._secret_context, raw)
                decrypted_float = enc.decrypt()[0]
                result[field] = self._restore_type(decrypted_float, blob.get("original_type"))
            except Exception as exc:
                logger.warning("Failed to decrypt field %r: %s — leaving encrypted", field, exc)
                still_encrypted.append(field)
                continue

            if field in encrypted_fields:
                encrypted_fields.remove(field)

        if encrypted_fields:
            result["__fhe_encrypted_fields__"] = sorted(encrypted_fields)
        else:
            result.pop("__fhe_encrypted_fields__", None)
            result.pop("__fhe_context__", None)

        return result

    def __repr__(self) -> str:
        return f"HomomorphicDecryptionTransformer(fields={len(self.fields)}, key_dir={self.key_dir!r})"
